#!/bin/sh

# File: build-deb  [wrapper for 'dn-build-deb']


# PARAMETERS

# root directory of project
root="/home/david/data/computing/projects/libs/curses-widget-listbox-dnlistbox"

# package name
pkg="libcurses-widget-listbox-dnlistbox"

# package maintainer's name
name="David Nebauer"

# package maintainer's email address
email="david@nebauer.org"


# RUN SCRIPT

dn-build-deb -r "${root}" -p "${pkg}" -n "${name}" -e "${email}"
