#!/usr/bin/perl

use Moo;                                  # {{{1
use strictures 2;
use 5.038_001;
use namespace::clean;
use version; our $VERSION = qv('0.1');    # }}}1

{

  package Dn::Internal;

  use Moo;                                # {{{1
  use MooX::Options;
  use namespace::clean -except => [ '_options_data', '_options_config' ];
  use Const::Fast;
  use Dn::CommonBash;
  my $cb = Dn::CommonBash->new();

  const my $TRUE  => 1;
  const my $FALSE => 0;
  const my $OPT_S => 's';                 # }}}1

  # Options

  # master     (-m) {{{1
  option 'master' => (
    is            => 'rw',
    format        => $OPT_S,
    required      => $TRUE,
    short         => 'm',
    documentation => 'Root file in dncommon-bash library',
  );

  # dictionary (-d) {{{1
  option 'dictionary' => (
    is            => 'rw',
    format        => $OPT_S,
    required      => $TRUE,
    short         => 'd',
    documentation => 'Vim dictionary file to be written',
  );

  # loader     (-l) {{{1
  option 'loader' => (
    is            => 'rw',
    format        => $OPT_S,
    required      => $TRUE,
    short         => 'l',
    documentation => 'Vim loader script to be written',
  );

  # store      (-s) {{{1
  option 'store' => (
    is            => 'rw',
    format        => $OPT_S,
    required      => $TRUE,
    short         => $OPT_S,
    documentation => 'Perl persistent data store',
  );    # }}}1

  # Methods

  # run() {{{1
  #
  # does:   load function data and write files
  # params: nil
  # prints: feedback
  # return: nil
  sub run ($self) {
    $cb->write_dictionary($self->dictionary, $self->master);
    $cb->write_loader($self->loader, $self->master);
    $cb->write_store($self->store, $self->master);
    return $TRUE;
  }    # }}}1

}

my $p = Dn::Internal->new_with_options->run;

1;

# POD {{{1

__END__

=head1 NAME

gen-helper-files - create build files for dncommon-bash library

=head1 USAGE

B<gen-helper-files> I<-m> master I<-d> dictionary I<-l> loader I<-s> store

B<gen-helper-files -h>

=head1 DESCRIPTION

This script takes as input the master file in the libdncommon-bash library. It
then creates three files:

=over 4

=over

=item dictionary

Used by Vim in handling the dncommon-bash library. This is a simple sorted list
of functions used as a dictionary file.

=item loader script

Used by Vim in handling the dncommon-bash library. This is a script which, when
run, loads a vim data structure with function information that can be used by Vim.

=item store

A perl-based persistent data store of the function data for use by perl scripts
accessing function data.

=back

=back

=head1 CONFIGURATION

This script requires no configuration files or environmental variables.

=head1 REQUIRED ARGUMENTS

=head2 --master -m

Master (root) file in dncommon-bash library.

Required. Filepath.

=head2 --dictionary -d

Vim dictionary file to be written.

Required. Filepath.

=head2 --loader -l

Vim loader script to be written.

Required. Filepath.

=head2 --store -s

Perl persistent data store to be written.

Required. Filepath.

=head1 OPTIONS

Nil.

=head1 EXIT STATUS

The exit code is 0 for successful execution and 1 if the script does a
controlled exit following an error. If the script crashes unexpectedly
the error code is that given by the system.

=head1 DIAGNOSTICS

This script is a wrapper for several functions from the Dn::CommonBash module.
See L<Dn::CommonBash/DIAGNOSTICS> for the diagnostic messages it emits.

=head1 INCOMPATIBILITIES

None reported.

=head1 BUGS AND LIMITATIONS

Please report any bugs to the author.

=head1 DEPENDENCIES

Const::Fast, Dn::CommonBash, Moo, MooX::Options, namespace::clean, strictures,
version.

=head1 AUTHOR

David Nebauer E<lt>david@nebauer.orgE<gt>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2024 David Nebauer E<lt>david@nebauer.orgE<gt>

This script is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
# vim: fdm=marker :
