#!/bin/bash

# File: tar-dir-prepare

# Package: dn-cronsudo

# This script will be run by dn-build-deb just prior to
# building the source distribution in 'tarball/build'.

# This script is run from the directory
# '/home/david/data/computing/projects/libs/common-bash/tarball/build'.

#############################################################

# VARIABLES

x_root='/home/david/data/computing/projects/libs/common-bash'
x_funcdict="$(pwd)/vim/funcdict.in"
x_funcload="$(pwd)/vim/funcload.vim.in"
x_libmaster="$(pwd)/libs/liball.in"
x_storage="$(pwd)/store/perlfuncdata.in"
x_gen_script="$x_root/debianise/scripts/gen-helper-files"
x_exit_status=true

# MAIN

# generate dictionary and vim function loader files
echo 'Creating application helper files'
echo '----------------------------------'
${x_gen_script} \
	-m "${x_libmaster}" \
	-d "${x_funcdict}" \
	-l "${x_funcload}" \
	-s "${x_storage}" ||
	x_exit_status=false
echo '----------------------------------'

unset x_funcdict x_funcload x_libmaster x_gen_script x_storage

if [[ $x_exit_status = false ]]; then
	echo 'Creation of application helper files failed' 1>&2
	exit 1
fi
