package Role::Utils::Dn::ConfigFile;

# modules/constants    {{{1
use Moo;
use strictures 2;
use 5.038_001;
use version; our $VERSION = qv('0.8');
use namespace::clean;

use Carp;
use Config::Any;
use Const::Fast;
use File::ConfigDir;
use MooX::HandlesVia;
use Types::Path::Tiny;

const my $TRUE                   => 1;
const my $FALSE                  => 0;
const my $MSG_SCALAR_NOT_HASHREF => 'Expected hashref, got: scalar';
const my $REF_TYPE_HASH          => 'HASH';                            # }}}1

# attributes

# stem    {{{1
has 'stem' => (
  is       => 'ro',
  isa      => Types::Standard::Str,
  required => $TRUE,
  doc      => 'Basename of configuration file',
);

# suffixes, _suffixes    {{{1
has 'suffixes' => (
  is       => 'ro',
  isa      => Types::Standard::ArrayRef [Types::Standard::Str],
  required => $FALSE,
  default  => sub {
    return [
      'rc',    '.rc',  '.cnf', '.conf', '.ini',
      '.json', '.jsn', '.xml', '.yaml', '.yml',
    ];
  },
  handles_via => 'Array',
  handles     => { _suffixes => 'elements' },
  doc         => 'Possible suffixes for config file name',
);

# silent    {{{1
has 'silent' => (
  is       => 'ro',
  isa      => Types::Standard::Bool,
  required => $FALSE,
  default  => $FALSE,
  doc      => 'Whether to provide non-error feedback',
);

# _conf_fp    {{{1
has '_conf_fp' => (
  is     => 'lazy',
  isa    => Types::Path::Tiny::AbsPath,
  coerce => Types::Path::Tiny::AbsPath->coercion,
  doc    => 'Path of configuration file (must exist)',
);

sub _build__conf_fp($self) {    ## no critic (Subroutines::ProhibitUnusedPrivateSubroutines)
  my $stem = $self->stem;
  croak 'No stem name provided' if not $stem;
  my @candidate_dirs = File::ConfigDir::config_dirs();
  croak 'Unable to generate list of candidate configuration directories'
      if not @candidate_dirs;
  my @suffixes = $self->_suffixes;

  # generate list of candidate config filepaths
  my @candidate_fps;
  for my $dir (@candidate_dirs) {
    for my $suffix (@suffixes) {
      push @candidate_fps, "$dir/$stem$suffix", "$dir/$stem/$stem$suffix";
    }
  }

  # get config data from any found candidate filepaths
  # • Config::Any returns a data structure like:
  #     [
  #       { '/home/david/rtng.json' => { $config_data_hashref } },
  #       { '/home/david/.config/rtng.ini' => { $config_data_hashref } }
  #     ]
  my $conf_matches =
      Config::Any->load_files(
    { files => [@candidate_fps], use_ext => $TRUE });
  croak 'No configuration files located' if not @{$conf_matches};

  # extract filepaths
  my @config_fps = map { (keys %{$_})[0] } @{$conf_matches};

  # use first match and report on extra matches
  my $config_fp = shift @config_fps;
  if (not $self->silent) {
    say "Using configuration file: $config_fp" or croak;
  }
  if (@config_fps and not $self->silent) {
    say "Multiple configuration files located based on stem '$stem'" or croak;
    say 'Ignoring:'                                                  or croak;
    for my $fp (@config_fps) {
      say "- $fp" or croak;
    }
  }

  return $config_fp;
}

# data    {{{1
has 'data' => (
  is  => 'lazy',
  isa => Types::Standard::HashRef,
  doc => 'Configuration data returned by Config::Any',
);

sub _build_data($self) {    ## no critic (Subroutines::ProhibitUnusedPrivateSubroutines)

  # used for checking variable type
  my $var_type;

  # assume config file exists
  my $conf_fp = $self->_conf_fp;

  # • need 'use_ext => $TRUE'
  #   - if omitted get extraneous warning:
  #       use_ext argument was not explicitly set, as of 0.09, \
  #       this is true by default at /usr/share/perl5/Config/Any.pm \
  #       line 137.
  #   - if set to $FALSE, aberrant quoting destroys the data
  #   - note the following warning about use of 'use_ext':
  #       If the "use_ext" parameter is defined, the loader will attempt
  #       to parse the file extension from each filename and will skip
  #       the file unless it matches a standard extension for the
  #       loading plugins. Only plugins whose standard extensions match
  #       the file extension will be used. For efficiency reasons, its
  #       use is encouraged, but be aware that you will lose flexibility
  #       -- for example, a file called "myapp.cfg" containing YAML data
  #       will not be offered to the YAML plugin, whereas "myapp.yml" or
  #       "myapp.yaml" would be.
  #   - the error generated by a non-standard extension like 'cfg' is:
  #       There are no loaders available for .cfg files at \
  #       /home/david/tmp/dncommon/test.pl line 137.
  #   - a mismatch between loader (selected based on file extension) and
  #     internal file format may not generate an error when loading config
  #     file data, but it may misinterpret it, leading either to a failure
  #     to find a section/key value or to returning an incorrect value
  my $loaded_data =
      Config::Any->load_files({ files => [$conf_fp], use_ext => $TRUE });

  # expect to get data structure like: [ { 'conf_fp' => { <conf_data> } } ]
  # • get enclosed hashref
  my $length = scalar @{$loaded_data};
  croak "Expected array with 1 element, got ${length}" if $length != 1;
  my @loaded_data_list = @{$loaded_data};
  my $fp_data_hashref  = $loaded_data_list[0];
  $var_type = ref $fp_data_hashref;
  croak $MSG_SCALAR_NOT_HASHREF if $var_type eq q{};
  croak "Expected HASH reference, got: $var_type"
      if $var_type ne $REF_TYPE_HASH;

  # • get config data (the hashref value)
  my %fp_data_hash        = %{$fp_data_hashref};
  my @fp_data_hash_values = values %fp_data_hash;
  my $conf_data           = $fp_data_hash_values[0];
  $var_type = ref $conf_data;
  croak $MSG_SCALAR_NOT_HASHREF if $var_type eq q{};
  croak "Expected HASH reference, got: $var_type"
      if $var_type ne $REF_TYPE_HASH;

  return $conf_data;
}    # }}}1

# methods

# get_value($key, [$section])    {{{1
#
# does:   get configuration file value for given key
# params: key     - config key [string, required]
#         section - config file section
#                   [string, optional, default='default']
# prints: feedback on error
# return: scalar arrayref, dies on failure
sub get_value ($self, $key, $section = 'default') {

  # get section data
  my $conf_data_ref = $self->data;
  my %conf_data     = %{$conf_data_ref};
  croak "No config section named '$section'"
      if not exists $conf_data{$section};
  croak "No config section named '$section'"
      if not defined $conf_data{$section};
  my $sect_data_ref  = $conf_data{$section};
  my $sect_data_type = ref $sect_data_ref;
  croak $MSG_SCALAR_NOT_HASHREF if $sect_data_type eq q{};
  croak "Expected HASH reference, got: $sect_data_type"
      if $sect_data_type ne $REF_TYPE_HASH;
  my %sect_data = %{$sect_data_ref};

  # get key value within section
  croak "No key named '$key' in section '$section'"
      if not exists $sect_data{$key};
  croak "No key named '$key' in section '$section'"
      if not defined $sect_data{$key};
  my $value = $sect_data{$key};

  return $value;
}    # }}}1

1;

# POD    {{{1

__END__

=head1 NAME

Role::Utils::Dn::ConfigFile - returned by Role::Utils::Dn->config_file()

=head1 SYNOPSIS

    with qw(Role::Utils::Dn);

    my $stem = 'my_config';
    my $cfg = $self->config_file($stem);

    # retrieve all config file data as a hashref
    my $all_conf_data = $cfg->data;

    # retrieve a single config file value
    my $conf_value = $cfg->get_value($my_key, $my_section);

=head1 VERSION

This documentation refers to Role::Utils::Dn::CommandResult version 0.8.

=head1 DESCRIPTION

Captures results of running a command with the C<Role::Utils::Dn> method
C<config_file>.

=head2 Selecting configuration file

The resulting object makes available configuration file data.
The configuration file used is based on a provided "stem".

The steps followed to select a configuration file are:

=over

=item

The module L<File::ConfigDir> generates a list of possible configuration
directories.

=item

A list of file suffixes, such as F<rc> and F<.ini>, is obtained from the
calling script or, if none are provided, a default list.

=item

For every combination of configuration directory and file suffix, the
following are added to a list of candidate configuration filepaths:

=over

=item

F<$dir/$stem$suffix>

=item

F<$dir/$stem/$stem$suffix>

=back

=item

The first candidate filepath which is found to exist is used.

=back

=head2 Reading the configuration file

The module L<Config::Any> is used to extract data from the chosen
configuration file. This module, in turn, uses other modules to read the
configuration file depending on the file format, for example,
L<JSON::MaybeXS> for json data or L<Config::Tiny> for ini data.

A quirk of L<Config::Any>'s operation means that the configuration file's
extension is used as a short-cut to determine data format and, in turn,
the loader module to use. For example, if a file has a F<.json> extension
the L<JSON::MaybeXS> loader module is used.

This means a non-specific file extension like F<.cfg> will cause a fatal
"no loaders available" error.

While more extensive testing is required to confirm this, it appears that
file suffixes like F<rc>, F<.rc>, F<.cnf> and F<.conf> are considered to
be formatted like Apache configuration files. This format is documented in
numerous locations, including the
L<Apache http server project|https://httpd.apache.org/docs/current/configuring.html>.

B<Warning:> When reading the configuration file a mismatch between the
inferred file format and the actual data format may not be detected. The
file may instead be incorrectly parsed and erroneous data returned by the
objects's C<data> attribute, while the C<get_value> method may return an
incorrect key value of mistakenly report that there is no matching key in
the file.

=head1 SUBROUTINES/METHODS

=head2 get_value($key[, $section])

=head3 Purpose

Gets a single configuration file value.

=head3 Parameters

=over

=item $key

Name of configuration file key. Scalar string. Required.

B<Warning:> Key names are case sensitive.

B<Warning:> A fatal error occurs if the key is not found.

=item $section

Name of configuration file section. Scalar string. Optional.
Default: 'default'.

B<Warning:> A fatal error occurs if the section is not found.
This includes the "default" section if no section name if provided.

B<Warning:> Section names are case sensitive.

=back

=head3 Prints

Error messages on failure.

=head3 Returns

Configuration file value. Scalar or reference, depending on data configuration.

=head1 CONFIGURATION AND ENVIRONMENT

=head2 Properties

The C<stem>, C<silent> and C<suffixes> attributes are provided at startup.

The C<data> attribute is generated at object instantiation and is available
to the calling script.

=head3 stem

Configuration file stem provided at object construction. Scalar string.

=head3 silent

Whether to suppress informational messages about which configuration files
were located and which one was selected, provided at object construction.
Scalar boolean. Optional. Default: false.

=head3 suffixes

File extensions or endings that the configuration file may have, provided at
object construction. Arrayref. Optional.

Default arrayref contents:

=over

=item

F<rc>

=item

F<.rc>

=item

F<.cnf>

=item

F<.conf>

=item

F<.ini>

=item

F<.json>

=item

F<.jsn>

=item

F<.xml>

=item

F<.yaml>

=item

F<.yml>

=back

=head3 data

The extracted configuration data. Hashref.

=head2 Configuration files

None used.

=head2 Environment variables

None used.

=head1 DIAGNOSTICS

Unless otherwise noted, all messages documented here are fatal.

=head2 Expected array with 1 element, got NUM

=head2 Expected hashref, got: scalar

=head2 Expected HASH reference, got: VAR_TYPE

These errors occur when the configuration file is being read and the data
is in an unexpected format.

=head2 No config section named NAME

The C<get_value> method gives this error if it cannot locate the
specified section in the configuration file data.

=head2 No configuration files located

Occurs if none of the combinations of candidate configuration directories,
file stem, and suffixes result in a locatable filepath.

Troubleshooting steps include checking that the:

=over

=item file stem is spelled correctly

=item configuration file is in a standard configuration directory

=item file suffix is included in the list of checked suffixes.

=back

=head2 No key named NAME in section NAME

The C<get_value> method gives this error if it cannot locate the
specified section/key in the configuration file data.

=head2 No stem name provided

Occurs if no file stem provided at object construction.

=head2 There are no loaders available for .EXT files

As noted in the L</DESCRIPTION> section, to read the configuration file
the L<Config::Any> module infers the configuration file's data format from
it's file extension and selects an appropriate module to use as a loader.
This error message occurs if L<Config::Any> is unable to match a loader
module to the file extension. See the L<Config::Any> documentation for
more details.

=head2 Unable to generate list of candidate configuration directories

Occurs if L<File::ConfigDir> fails to generate any candidate configuration
directories.

=head1 INCOMPATIBILITIES

None known.

=head1 BUGS AND LIMITATIONS

None reported.

=head1 DEPENDENCIES

=head2 Perl modules

Carp, Config::Any, Const::Fast, File::ConfigDir, Moo, MooX::HandlesVia,
namespace::clean, strictures, Types::Path::Tiny, version.

=head1 BUGS AND LIMITATIONS

Please report any bugs to the author.

=head1 AUTHOR

L<David Nebauer|mailto:davidnebauer@hotkey.net.au>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2026 L<David Nebauer|mailto:davidnebauer@hotkey.net.au>

This script is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

# }}}1

# vim:fdm=marker
