#!/bin/sh

# File: build-deb  [wrapper for 'dn-build-deb']


# PARAMETERS

# root directory of project
root="/home/david/data/computing/projects/libs/common-vars"

# package name
pkg="libdncommon-vars"

# package maintainer's email address
email="david@nebauer.org"


# RUN SCRIPT

dn-build-deb -r "${root}" -p "${pkg}" -e "${email}"
