#!/bin/sh

# File: deb-dir-prepare

# Package: libdncommon-vars

# This file will be sourced by dn-build-deb after copying customised
# debian control files to the debian package source and just prior
# to building the package.  The cwd directory during the sourcing is
# '/home/david/data/computing/projects/libs/dncommon-vars/debianise/source/<archive>'
# where <archive> is the top-level directory in the source project
# tarzipped distribution built in 'tarball/build'.  Must be in same
# dir when finished.

# Some useful variables available to this file are:
#   pkg         - package name
#   root        - directory: project root
#   tar_build   - directory: <root>/tarball/build
#   deb_scripts - directory: <root>/debianise/scripts
#   deb_source  - directory: <root>/debianise/source
#   source_base - directory: <root>/debianise/source/archive

####################################################################

